import {webkit,chromium} from '@playwright/test';
import assert from 'node:assert/strict';import fs from 'node:fs/promises';import {blank} from '../docs/iphone/app/model.mjs';
const base=process.env.TEST_BASE_URL||'http://127.0.0.1:4173',key='patterncanvas-iphone-v1';
await fs.mkdir('test-results',{recursive:true});
const browser=await webkit.launch();const context=await browser.newContext({viewport:{width:390,height:844},deviceScaleFactor:1,isMobile:true,hasTouch:true});
await context.addInitScript(p=>{if(location.protocol.startsWith('http')&&!localStorage.getItem('patterncanvas-iphone-v1'))localStorage.setItem('patterncanvas-iphone-v1',JSON.stringify(p));},blank(3,3));
const page=await context.newPage(),errors=[];page.on('pageerror',e=>errors.push(e.message));page.on('dialog',d=>d.accept());const state=()=>page.evaluate(k=>JSON.parse(localStorage.getItem(k)),key);
try{
 await page.goto(base+'/iphone/app/');await page.waitForFunction(()=>!!navigator.serviceWorker.controller);
 const before=(await state()).cells;await page.locator('#chart-lock').click();await page.locator('#chart').click({position:{x:84,y:12}});assert.deepEqual((await state()).cells,before);await page.locator('#complete').click();assert.equal((await state()).currentRow,2);await page.reload();assert.equal(await page.locator('#chart-lock').getAttribute('aria-pressed'),'true');assert.ok(await page.locator('#stitch-edit').isDisabled());await page.locator('#chart-lock').click();
 await page.locator('#readability-open').click();await page.locator('#row-color-presets button').filter({hasText:'黄'}).click();await page.locator('#row-width').selectOption('6');await page.locator('#readability-dialog .primary').click();
 const pixels=await page.locator('#chart').evaluate(c=>{const g=c.getContext('2d');return[[40,60],[90,27],[84,60]].map(([x,y])=>Array.from(g.getImageData(x,y,1,1).data).slice(0,3));});assert.deepEqual(pixels[0],[20,101,52]);assert.deepEqual(pixels[1],[255,230,0]);assert.deepEqual(pixels[2],[243,234,217]);assert.deepEqual((await state()).cells,before);
 await page.reload();assert.deepEqual(await page.evaluate(()=>JSON.parse(localStorage.getItem('patterncanvas-readability'))),{color:'#ffe600',width:6});
 await page.locator('#chart').click({position:{x:84,y:300}});assert.deepEqual((await state()).cells,before);
 await page.locator('#stitch-edit').click();await page.locator('#structure-row').fill('2');await page.locator('#structure-count').fill('1');await page.locator('#structure-apply').click();assert.deepEqual((await state()).cells,[[0,0,0,null],[0,0,0,1],[0,0,0,1]]);
 await page.locator('#undo').click();assert.deepEqual((await state()).cells,before);await page.locator('#redo').click();assert.equal((await state()).columns,4);await page.reload();assert.equal((await state()).cells[0][3],null);
 await page.locator('#direction-open').click();await page.locator('#direction-top').click();await page.locator('#stitch-edit').click();await page.locator('#structure-action').selectOption('add-rows');await page.locator('#structure-row').fill('2');await page.locator('#structure-count').fill('1');await page.locator('#structure-apply').click();assert.equal((await state()).rows,4);assert.equal((await state()).currentRow,4);assert.ok((await state()).topDown);
 await page.screenshot({path:'test-results/web-updates-phone.png',fullPage:true});console.log('PASS: lock/restart, custom frame pixels, visible completion without hiding yarn colors, footer, shaping/undo/restart/top-down');
 await page.locator('[data-view=settings]').click();const image=await page.evaluate(()=>{const c=document.createElement('canvas');c.width=160;c.height=80;const g=c.getContext('2d');g.fillStyle='#ff0000';g.fillRect(0,0,120,80);g.fillStyle='#0000ff';g.fillRect(120,0,40,80);return c.toDataURL().split(',')[1];});
 await page.locator('#image-file').setInputFiles({name:'two-colors.png',mimeType:'image/png',buffer:Buffer.from(image,'base64')});await page.locator('#image-convert').waitFor({state:'visible'});await page.waitForFunction(()=>!document.getElementById('image-convert').disabled);
 await page.locator('#image-sizes button').first().click();await page.waitForFunction(()=>document.getElementById('image-result-info').textContent==='変換結果：40目 × 20段・2色');assert.match(await page.locator('#image-recommended').textContent(),/おすすめ 2色/);await page.locator('#image-recommended').click();await page.waitForFunction(()=>!document.getElementById('image-convert').disabled);assert.equal(await page.locator('#image-colors').inputValue(),'2');
 await page.locator('#image-more').click();await page.waitForFunction(()=>!document.getElementById('image-convert').disabled);assert.equal(await page.locator('#image-colors').inputValue(),'3');await page.locator('#image-less').click();await page.waitForFunction(()=>!document.getElementById('image-convert').disabled);
 const rendered=await page.locator('#image-result').evaluate(c=>[0,c.width-1].map(x=>Array.from(c.getContext('2d').getImageData(x,0,1,1).data)));assert.deepEqual(rendered,[[255,0,0,255],[0,0,255,255]]);
 for(const [width,height] of [[320,480],[640,360],[390,844]]){await page.setViewportSize({width,height});const result=await page.locator('#image-convert').boundingBox(),cancel=await page.locator('#image-dismiss').boundingBox();for(const rect of [result,cancel])assert.ok(rect.x>=0&&rect.y>=0&&rect.x+rect.width<=width&&rect.y+rect.height<=height&&rect.height>=48,JSON.stringify(rect));assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));}
 await page.addStyleTag({content:'.image-import-dialog button,.image-import-dialog label,.image-import-dialog p{font-size:20px!important}'});const rect=await page.locator('#image-convert').boundingBox();assert.ok(rect.y+rect.height<=844);await page.screenshot({path:'test-results/web-image-modal.png'});
 await page.locator('#image-width').fill('0');assert.ok(await page.locator('#image-convert').isDisabled());await page.locator('#image-width').fill('40');await page.waitForFunction(()=>!document.getElementById('image-convert').disabled);
 await page.locator('#image-convert').click();assert.equal((await state()).columns,40);assert.equal((await state()).rows,20);assert.deepEqual(new Set((await state()).yarns.map(y=>y.color)),new Set(['#ff0000','#0000ff']));await page.reload();assert.equal((await state()).columns,40);assert.equal(await page.evaluate(()=>localStorage.getItem('patterncanvas-image-colors')),'2');
 console.log('PASS: exact imported colors, recommendation/size/presets, result orientation, stale-result prevention, small/landscape/large-text modal, import/restart');
 const desktop=await browser.newContext({viewport:{width:1200,height:800}}),wide=await desktop.newPage();wide.on('pageerror',e=>errors.push(e.message));await wide.goto(base+'/iphone/app/');await wide.locator('[data-view=both]').click();assert.ok(await wide.locator('#settings').isVisible());const settingsBefore=await wide.locator('#settings').evaluate(e=>e.scrollTop);await wide.locator('#work').evaluate(e=>e.scrollTop=0);const work=await wide.locator('#work').boundingBox();await wide.mouse.move(work.x+6,work.y+100);await wide.mouse.wheel(0,400);await wide.waitForFunction(()=>document.getElementById('work').scrollTop>0);assert.equal(await wide.locator('#settings').evaluate(e=>e.scrollTop),settingsBefore);await wide.screenshot({path:'test-results/web-updates-wide.png'});await desktop.close();console.log('PASS: wide both-view right-side scrolling independent from settings');assert.deepEqual(errors,[]);
}finally{await browser.close();}
// Chromium supports reliable offline emulation for service worker/worker modules on Windows.
const offlineBrowser=await chromium.launch({channel:process.env.TEST_CHROMIUM_CHANNEL||undefined});const offline=await offlineBrowser.newContext();const op=await offline.newPage();try{await op.goto(base+'/iphone/app/');await op.waitForFunction(()=>!!navigator.serviceWorker.controller);await offline.setOffline(true);await op.reload();await op.locator('[data-view=settings]').click();await op.locator('#image-file').setInputFiles('docs/iphone/app/icon-192.png');await op.waitForFunction(()=>!document.getElementById('image-convert').disabled);assert.match(await op.locator('#image-result-info').textContent(),/変換結果/);console.log('PASS: offline app and image conversion worker');}finally{await offlineBrowser.close();}
