import {webkit} from '@playwright/test';
import assert from 'node:assert/strict';
import {blank} from '../docs/iphone/app/model.mjs';
const browser=await webkit.launch();
const context=await browser.newContext({viewport:{width:390,height:844},isMobile:true,hasTouch:true});
await context.route('**/platform.mjs',route=>route.fulfill({contentType:'text/javascript',body:`
export const native=true;
export const readProject=()=>localStorage.getItem('patterncanvas-iphone-v1');
export const writeProject=data=>{localStorage.setItem('patterncanvas-iphone-v1',data);window.nativeSaves=(window.nativeSaves||0)+1;};
export const readLock=()=>localStorage.getItem('native-lock')==='true';
export const writeLock=value=>localStorage.setItem('native-lock',String(value));
export const rowCompleted=()=>window.haptics=(window.haptics||0)+1;
export const exportProject=async(data,name)=>{window.shared={data,name};};
export const prepareOffline=()=>document.querySelector('#offline-state').textContent='初回からオフラインで使えます';
`}));
const page=await context.newPage(),errors=[],remote=[];page.on('dialog',d=>d.accept());page.on('pageerror',e=>errors.push(e.message));page.on('request',r=>{if(!r.url().startsWith('http://127.0.0.1:4175')&&!r.url().startsWith('blob:http://127.0.0.1:4175/'))remote.push(r.url());});
try{
  await page.goto('http://127.0.0.1:4175/');await page.locator('#chart').waitFor();
  assert.equal(await page.locator('#chart-mirror').count(),0);
  const original=await page.evaluate(()=>localStorage.getItem('patterncanvas-iphone-v1'));
  const previewBefore=await page.locator('#preview').evaluate(c=>c.toDataURL());
  await page.locator('#column-numbering').selectOption('right');
  assert.equal(await page.locator('#preview').evaluate(c=>c.toDataURL()),previewBefore);
  assert.equal(await page.evaluate(()=>localStorage.getItem('patterncanvas-iphone-v1')),original);
  await page.evaluate(()=>localStorage.setItem('patterncanvas-chart-mirrored','true'));
  await page.reload();await page.locator('#chart').waitFor();
  assert.equal(await page.locator('#column-numbering').inputValue(),'right');
  await page.locator('#chart-lock').click();
  await page.locator('#column-numbering').selectOption('left');
  await page.locator('#chart-lock').click();
  console.log('PASS numbering persists, works while locked, preserves project and preview; turn control removed');

  assert.equal(await page.getByText('購入する',{exact:true}).count(),0);
  await page.locator('#complete').click();assert.equal(await page.evaluate(()=>window.haptics),1);assert((await page.evaluate(()=>window.nativeSaves))>0);
  await page.locator('#chart-lock').click();await page.reload();await page.waitForFunction(()=>document.querySelector('#chart-lock').getAttribute('aria-pressed')==='true');
  await page.locator('[data-view=settings]').click();await page.locator('#export').click();
  const shared=await page.evaluate(()=>window.shared);assert.equal(JSON.parse(shared.data).currentRow,2);assert(shared.name.endsWith('.json'));
  await page.getByRole('link',{name:'プライバシーポリシー',exact:true}).click();await page.getByRole('heading',{name:'プライバシーポリシー'}).waitFor();
  await page.getByRole('link',{name:'編み図へ戻る',exact:true}).click();await page.locator('#chart').waitFor();
  assert.equal(await page.evaluate(()=>JSON.parse(localStorage.getItem('patterncanvas-iphone-v1')).currentRow),2);
  await page.locator('#chart-lock').click();await page.locator('[data-view=settings]').click();
  await page.locator('[data-view=both]').click();
  await page.locator('#direction-open').click();await page.locator('#direction-top').click();
  const top=await page.evaluate(()=>JSON.parse(localStorage.getItem('patterncanvas-iphone-v1')));assert.equal(top.currentRow,top.rows*top.verticalRepeats);assert.ok(top.topDown);
  await page.locator('#complete').click();await page.reload();assert.equal(await page.evaluate(()=>JSON.parse(localStorage.getItem('patterncanvas-iphone-v1')).currentRow),top.currentRow-1);
  await page.locator('#readability-open').click();await page.locator('#row-color-presets button').filter({hasText:'黄'}).click();await page.locator('#row-width').selectOption('6');await page.locator('#readability-dialog .primary').click();
  await page.locator('#stitch-edit').click();await page.locator('#structure-row').fill('2');await page.locator('#structure-count').fill('1');await page.locator('#structure-apply').click();
  const shape=await page.evaluate(()=>JSON.parse(localStorage.getItem('patterncanvas-iphone-v1')));assert.equal(shape.cells.at(-1).at(-1),null);assert.notEqual(shape.cells[0].at(-1),null);
  await page.locator('[data-view=settings]').click();
  const image=await page.evaluate(()=>{const c=document.createElement('canvas');c.width=160;c.height=80;const g=c.getContext('2d');g.fillStyle='red';g.fillRect(0,0,120,80);g.fillStyle='blue';g.fillRect(120,0,40,80);return c.toDataURL().split(',')[1];});
  await page.locator('#image-file').setInputFiles({name:'two-colors.png',mimeType:'image/png',buffer:Buffer.from(image,'base64')});await page.waitForFunction(()=>!document.getElementById('image-convert').disabled);
  await page.locator('#image-sizes button').first().click();await page.waitForFunction(()=>document.getElementById('image-result-info').textContent==='変換結果：40目 × 20段・2色');await page.locator('#image-recommended').click();await page.waitForFunction(()=>!document.getElementById('image-convert').disabled);
  for(const size of [{width:320,height:480},{width:640,height:360}]){await page.setViewportSize(size);const r=await page.locator('#image-convert').boundingBox();assert(r.y>=0&&r.y+r.height<=size.height&&r.height>=48);}
  await page.locator('#image-convert').click();await page.reload();const imported=await page.evaluate(()=>JSON.parse(localStorage.getItem('patterncanvas-iphone-v1')));assert.equal(imported.columns,40);assert.equal(imported.rows,20);assert.deepEqual(new Set(imported.yarns.map(y=>y.color)),new Set(['#ff0000','#0000ff']));
  assert.deepEqual(await page.evaluate(()=>JSON.parse(localStorage.getItem('patterncanvas-readability'))),{color:'#ffe600',width:6});
  await page.locator('[data-view=settings]').click();await page.locator('#export').click();assert.equal(JSON.parse((await page.evaluate(()=>window.shared)).data).rows,20);
  console.log('PASS native boundary: direction/restart, readability, top-down shaping, source colors, recommendations, small/landscape modal, native conversion path and share');

  const mirrorFixture={...blank(3,2),format:'patterncanvas-web-2'};
  await page.locator('#import').setInputFiles({name:'mirror.json',mimeType:'application/json',buffer:Buffer.from(JSON.stringify(mirrorFixture))});
  await page.locator('[data-view=chart]').click();
  await page.locator('#column-numbering').selectOption('right');
  const chosen=await page.locator('#palette button').nth(1).getAttribute('aria-label');
  await page.locator('#palette button').nth(1).click();
  await page.locator('#chart').click({position:{x:84,y:40}});
  const edited=await page.evaluate(()=>JSON.parse(localStorage.getItem('patterncanvas-iphone-v1')));
  assert.equal(edited.cells[1][0],edited.yarns.find(y=>y.name===chosen).id);
  assert.equal(edited.cells[1][2],mirrorFixture.cells[1][2]);
  await page.locator('#undo').click();
  assert.deepEqual(await page.evaluate(()=>JSON.parse(localStorage.getItem('patterncanvas-iphone-v1')).cells),mirrorFixture.cells);
  await page.locator('#redo').click();
  assert.deepEqual(await page.evaluate(()=>JSON.parse(localStorage.getItem('patterncanvas-iphone-v1')).cells),edited.cells);
  await page.locator('[data-tool=eraser]').click();await page.locator('#chart').click({position:{x:84,y:40}});
  assert.equal(await page.locator('#redo').isDisabled(),true,'A new edit clears redo');
  await page.locator('#undo').click();assert.deepEqual(await page.evaluate(()=>JSON.parse(localStorage.getItem('patterncanvas-iphone-v1')).cells),edited.cells);
  await page.locator('#redo').click();assert.deepEqual(await page.evaluate(()=>JSON.parse(localStorage.getItem('patterncanvas-iphone-v1')).cells),mirrorFixture.cells);
  await page.locator('[data-tool=fill]').click();await page.locator('#chart').click({position:{x:84,y:40}});
  const filled=await page.evaluate(()=>JSON.parse(localStorage.getItem('patterncanvas-iphone-v1')).cells);
  assert(filled.flat().every(id=>id===edited.cells[1][0]));
  await page.locator('#undo').click();assert.deepEqual(await page.evaluate(()=>JSON.parse(localStorage.getItem('patterncanvas-iphone-v1')).cells),mirrorFixture.cells);
  await page.locator('#redo').click();assert.deepEqual(await page.evaluate(()=>JSON.parse(localStorage.getItem('patterncanvas-iphone-v1')).cells),filled);
  await page.locator('#undo').click();
  await page.locator('#chart-lock').click();assert(await page.locator('#undo').isDisabled());assert(await page.locator('#redo').isDisabled());await page.locator('#chart-lock').click();
  await page.locator('#column-numbering').selectOption('left');
  await page.locator('[data-view=preview]').click();assert(await page.locator('#edit-history').isHidden());
  await page.locator('[data-view=settings]').click();assert(await page.locator('#edit-history').isHidden());
  console.log('PASS pen/eraser/fill undo-redo, new edit clears redo, lock disables history, preview/settings hide toolbar');
  console.log('PASS right-start numbering keeps edit coordinates unchanged and undo restores data');
  const large={...blank(500,500),format:'patterncanvas-web-2'},buffer=Buffer.from(JSON.stringify(large,null,2));assert(buffer.length>2000000);
  await page.locator('#import').setInputFiles({name:'large-chart.json',mimeType:'application/json',buffer});
  await page.waitForFunction(()=>JSON.parse(localStorage.getItem('patterncanvas-iphone-v1')).rows===500);
  for(const size of [{width:375,height:667},{width:430,height:932},{width:844,height:390}]){await page.setViewportSize(size);assert(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));}
  await page.locator('[data-view=both]').click();
  await page.locator('[data-view=chart]').click();
  await page.locator('#zoom-in').click();await page.locator('#zoom-in').click();
  await page.locator('[data-tool=pan]').click();
  const c=page.locator('#chart');await c.scrollIntoViewIfNeeded();
  await c.evaluate(canvas=>{
    const ctx=canvas.getContext('2d'),clear=ctx.clearRect.bind(ctx),text=ctx.fillText.bind(ctx);
    ctx.clearRect=(...args)=>{window.chartLabels=[];clear(...args);};
    ctx.fillText=(label,x,y,...args)=>{window.chartLabels.push({label,x,y});text(label,x,y,...args);};
  });
  const box=await c.boundingBox();
  await page.mouse.move(box.x+160,box.y+160);await page.mouse.down();await page.mouse.move(box.x+110,box.y+90,{steps:4});await page.mouse.up();
  const pannedBefore=await c.evaluate(c=>c.toDataURL());
  const previewPanned=await page.locator('#preview').evaluate(c=>c.toDataURL());
  const dataBeforeStroke=await page.evaluate(()=>JSON.parse(localStorage.getItem('patterncanvas-iphone-v1')).cells);
  await page.locator('#palette button').nth(1).click();await page.locator('[data-tool=pen]').click();await c.scrollIntoViewIfNeeded();
  const strokeBox=await c.boundingBox();
  await page.mouse.move(strokeBox.x+100,strokeBox.y+80);await page.mouse.down();await page.mouse.move(strokeBox.x+210,strokeBox.y+80,{steps:5});await page.mouse.up();
  const strokeData=await page.evaluate(()=>JSON.parse(localStorage.getItem('patterncanvas-iphone-v1')).cells);
  assert(strokeData.some((row,r)=>row.some((id,x)=>id!==dataBeforeStroke[r][x])),'Stroke must paint visible cells');
  for(const id of ['undo','redo']){
   const rect=await page.locator('#'+id).boundingBox(),tabs=await page.locator('.tabs').boundingBox();
   assert(rect.height>=44&&rect.width>=100&&rect.y>=0&&rect.y+rect.height<=tabs.y);
   assert(await page.locator('#'+id).evaluate(el=>{const r=el.getBoundingClientRect();return el.contains(document.elementFromPoint(r.x+r.width/2,r.y+r.height/2));}));
  }
  await page.locator('#undo').click();
  assert.deepEqual(await page.evaluate(()=>JSON.parse(localStorage.getItem('patterncanvas-iphone-v1')).cells),dataBeforeStroke,'One undo removes the entire stroke');
  assert.equal(await c.evaluate(c=>c.toDataURL()),pannedBefore,'Undo preserves zoom and pan');
  assert.equal(await page.locator('#preview').evaluate(c=>c.toDataURL()),previewPanned);
  await page.locator('#redo').click();assert.deepEqual(await page.evaluate(()=>JSON.parse(localStorage.getItem('patterncanvas-iphone-v1')).cells),strokeData);
  await page.locator('#undo').click();
  console.log('PASS chart-adjacent undo/redo reachable while drawing, whole-stroke history and unchanged pan/zoom/preview');
  await page.locator('#column-numbering').scrollIntoViewIfNeeded();
  const stateBefore=await page.evaluate(()=>({project:localStorage.getItem('patterncanvas-iphone-v1'),scrollY,work:document.getElementById('work').scrollTop}));
  const rail=y=>c.evaluate((canvas,y)=>window.chartLabels.filter(l=>l.y===(y==='top'?14:canvas.getBoundingClientRect().height-14)&&l.x>=72&&l.x<=canvas.getBoundingClientRect().width).map(l=>l.label),y);
  assert.deepEqual(await rail('top'),await rail('bottom'));
  const body=()=>c.evaluate(canvas=>{const crop=document.createElement('canvas'),dpr=canvas.width/canvas.getBoundingClientRect().width;crop.width=canvas.width;crop.height=canvas.height-56*dpr;crop.getContext('2d').drawImage(canvas,0,28*dpr,crop.width,crop.height,0,0,crop.width,crop.height);return crop.toDataURL();});
  const imageBefore=await body();
  await page.locator('#column-numbering').selectOption('right');
  assert.deepEqual(await rail('top'),await rail('bottom'));
  assert.equal(await body(),imageBefore,'Only numbers change; chart body stays pixel-identical');
  assert.deepEqual(await page.evaluate(()=>({project:localStorage.getItem('patterncanvas-iphone-v1'),scrollY,work:document.getElementById('work').scrollTop})),stateBefore);
  await page.locator('#column-numbering').selectOption('left');
  assert.equal(await body(),imageBefore);
  await c.click({position:{x:84,y:14}});
  assert.equal(await page.evaluate(()=>localStorage.getItem('patterncanvas-iphone-v1')),stateBefore.project,'Header tap must not edit or select a row');
  const gear=page.getByRole('button',{name:'段の色・線の太さを設定',exact:true});
  const gearBox=await gear.boundingBox();assert(gearBox.width>=44&&gearBox.height>=44);
  assert.equal(await gear.locator('svg[aria-hidden=true]').count(),1);assert.equal((await gear.textContent()).trim(),'');
  await gear.click();assert(await page.locator('#readability-dialog').isVisible());
  await page.locator('#readability-dialog .primary').click();
  console.log('PASS upper/lower numbers agree; direction leaves zoomed/panned chart unchanged; header is safe; gear opens settings');
  const canvasBefore=await c.evaluate(c=>c.toDataURL());const zoomBefore=await page.locator('#zoom-label').textContent();
  await page.locator('[data-view=chart]').dblclick();
  assert.equal(await c.evaluate(c=>c.toDataURL()),canvasBefore,'Repeated active tab must not recenter chart');
  assert.equal(await page.locator('#zoom-label').textContent(),zoomBefore);
  await c.scrollIntoViewIfNeeded();
  await c.dblclick({position:{x:20,y:80}});
  const selected=await page.evaluate(()=>JSON.parse(localStorage.getItem('patterncanvas-iphone-v1')).currentRow);
  await c.dblclick({position:{x:20,y:80}});
  assert.equal(await page.evaluate(()=>JSON.parse(localStorage.getItem('patterncanvas-iphone-v1')).currentRow),selected,'Repeated gutter tap must keep the selected row under the finger');
  for(const id of ['#work','.tabs button','body'])assert.equal(await page.locator(id).first().evaluate(e=>getComputedStyle(e).touchAction),'manipulation');
  assert.equal(await c.evaluate(e=>getComputedStyle(e).touchAction),'none');
  assert.equal(await page.evaluate(()=>visualViewport.scale),1);
  await page.locator('[data-view=both]').click();
  console.log('PASS repeated tabs retain pan/zoom; repeated row taps stay on the same row; double-tap page zoom disabled without disabling pinch');
  const beforeTablet=await page.evaluate(()=>localStorage.getItem('patterncanvas-iphone-v1'));
  for(const size of [{width:768,height:1024},{width:834,height:1194},{width:1024,height:768},{width:1366,height:1024},{width:507,height:1024},{width:320,height:768}]){
    await page.setViewportSize(size);await page.waitForTimeout(120);
    assert(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));
    const work=await page.locator('#work').boundingBox();assert(work.width>250);
    if(size.width>=740){
      const settings=await page.locator('#settings').boundingBox();assert(settings.x+settings.width<=work.x);assert(work.width>size.width*.4);
      for(const id of ['work','settings'])assert(await page.evaluate(id=>{const e=document.getElementById(id);e.scrollTop=100;return e.scrollTop>0;},id),id+' scrolls independently');
    }else assert(await page.locator('#settings').isHidden());
    assert.equal(await page.evaluate(()=>localStorage.getItem('patterncanvas-iphone-v1')),beforeTablet);
  }
  await page.setViewportSize({width:1024,height:768});
  await page.locator('[data-view=chart]').click();assert((await page.locator('#chart').boundingBox()).width>850);
  await page.locator('[data-view=preview]').click();assert((await page.locator('#preview').boundingBox()).width>850);
  await page.locator('[data-view=both]').click();await page.screenshot({path:'native/ipad-landscape.png'});
  console.log('PASS iPad portrait/landscape, Split View widths, independent panels, full-width chart/preview and project/progress preservation');
  assert.deepEqual(remote,[]);assert.deepEqual(errors,[]);console.log('PASS native UI with plugin boundary mocks: no remote requests, save, share, haptics, lock, privacy, restore, large exported chart import, rotation');
}finally{await browser.close();}
